### ISSUE TITLE
Bug in pay1_3_rpk & pay1_3_cert CDDL

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/EDHOC#10]
Section 4.2.3 - in pay1_3_rpk, ID_V should be ID_U.  Same issue for C_V in pay1_3_cert

Section 4.2.3 - combine pay1_3_rpk and pay1_3_cert into a single structure with an alternative option "ID_U: bstr / C_U:bstr" in the last line as the only difference is where the content comes from and not the structure of the array

**Comment by fpalombini** [comment]
Good catch!

**Comment by fpalombini** [comment]
Included in commit 007ba1c
