### ISSUE TITLE
Change the way that PartyUInfo and PartyVInfo are used

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/EDHOC#11]
Section 4.3 - Change the way that PartyUInfo and PartyVInfo are filled out as follows:
  - PartyUInfo SHALL contain: nonce shall be equal to N_U when deriving keys K_U* and N_V when deriving keys K_V*
  - PartyVInfo SHALL contain: nonce shall be equal to N_V when deriving keys K_U* and N_V when deriving keys K_U*

**Comment by fpalombini** [comment]
We are in the process to simplifying key derivation, which has an impact on this.

**Comment by fpalombini** [comment]
After update (commit 007ba1c ) this is not relevant anymore.
