### ISSUE TITLE
Negotiation/verification of method?

### ISSUE THREAD

**Issue by emanjon** [EricssonResearch/EDHOC#115]
The draft currently says that 

"Party U and Party V needs to have agreed on a single method to be used for EDHOC."

Is this enough for expected deployments of EDHOC. If not, is an attacker blocking one method to force use of a second method acceptable or does negotiation/verification of the selected method needed?

**Comment by gselander** [comment]
Migrated to https://github.com/lake-wg/edhoc/issues/11
