### ISSUE TITLE
Suggested re-organization of the document

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/EDHOC#14]
Section 4 - I would like to suggest the following reorg for the document
   Section X - Message #X - overview of what the message is going to accomplish - where it maps in the SIGMA-I protocol
   Section X.1 - Message structure - The CDDL description for the message
   Section X.2 - Message creation - 
       Section X.2.1 - For Async - 
       Section X.2.2 - For sync - use these two sections iff the differences are large
   Section X.3 - Message Processing Party->Message #X
   Section X.4 - Message Processing Message #X --> Party
            Again .3 and .4 can have subsections if the differences are large
   I would put the two key derivations (Section 5) steps as Section 5.1 and 5.2 (in protocol and post protocol)

**Comment by emanjon** [comment]
Organising by message, seems like a good idea.
- What would be the difference between "Message creation" and "Message Processing Party->Message #X"
- What do you mean with Async / sync?

**Comment by jimsch** [comment]
The difference was to reflect the current text where you have 
- Message Formating of Message 1
- Message Processing  U --> Message 1

Async/sync should have been Asym/Symm

**Comment by fpalombini** [comment]
We are considering this for the update after the next. But my doubt is that message 2 and message 3 may be different for symm-asym so to require sub-sections which would make the document hard to read.

**Comment by fpalombini** [comment]
Partly included in commit 007ba1c , we did keep symmetric and asymmetric separate though.

**Comment by jimsch** [comment]
Wrong commit referenced.

**Comment by fpalombini** [comment]
Right, I corrected it now. I have the feeling that the diff will not help much though, since the whole document was changed in that update.
