### ISSUE TITLE
Do considerations on multiple uses of ephemeral keys for multiple runs

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/EDHOC#16]
Discussions of a server using the same ephemeral key for multiple runs of the protocol.  Affects the PFS property, but this may be acceptable if the window is small (i.e. a couple of hours).

This is a potentally useful change that is common - See discussions in TLS 1.3

**Comment by fpalombini** [comment]
Do you mean that we should allow it or that we should add security considerations if that happens?

**Comment by jimsch** [comment]
You should discuss the security considerations and potentially allow it.  The problem is not always the issue of creating a fresh key, although that can be an issue in some cases, but saving time and energy as some of the work can be amortized over a number of conversations.

**Comment by emanjon** [comment]
Security consideration on reuse added in the latest upload.

**Comment by gselander** [comment]
In the case where ephemeral keys are allowed to be reused, the verification of nonce reuse should be made mandatory for the lifetime of the ephemeral key.

**Comment by mcr** [comment]
I'm happy with this: do not accept same nonce during lifetime of ephemeral key. If the mote runs out of space to store the nonces, then it should generate a new ephemeral key.  I think that the number of nonces that can be stored will be very small. Is there a reason to keep them other than checking for reuse?

**Comment by jimsch** [comment]
The major reason for keeping nonces is to prevent replay attacks.  As long as you make sure that your nonce is going to change if you re-use the same key, then there is no reason to keep the other side's nonce/key pairs.  

There are some interesting ways to generating new nonces that are going to be unique and non-sequential by using a counter and hash function.  The problem here is that you want the stream of nonces to be somewhat unpredictable.  Using MD5 or another short hash function would work.  Truncating SHA-256 would not give the uniqueness guarantee.  Moving to SHA-3 w/ the truncation built in would.
