### ISSUE TITLE
Replay is poorly defined

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/EDHOC#17]
Rules on replay of messages seems to be needed.  These rules may need to be modified by the difference between a reliable and an un-reliable transport.

**Comment by fpalombini** [comment]
It is not clear what replay protection we need: constrained devices will not be able to protect against replay of message_1 (DTLS is not protecting against replay of Client Hello), but an attacker will not be able to complete an EDHOC exchange. We are considering removing the part about verifying nonces for message_1.

**Comment by jimsch** [comment]
You need to re-read how the DTLS hello works.  There is a DOS attack that could be done with Client Hellos in DTLS that is mitigated by requiring that two be done by the client, the second with a challenge.  This defers the need for DTLS to do cryptographic operations until the second operation.  By mitigating the DOS attack, the work on replays for the client hello is dealt with.  The first one would generate a challenge which is cheap.  The second one will generate a cached reply so that the work is only done once. 

However, I am looking at when a cached response should be re-played and when things should be dropped on the floor and when errors should be returned.  Without this type of analysis it is difficult to tell what types of attacks are possible.

**Comment by emanjon** [comment]
I think there is a lot of new considerations here that are different from the standard DTLS deployment. Over wireless, generating a challenge and transmitting it is not cheap as transmitting, receiving and listening draw significant amounts of energy and transmitting the challenge blocks the radio from receiving data. In the PSK case cryptographic operations are dirt cheap, and in the asymmetric case, EdDSA is relatively cheap, at least much much cheaper than signing with RSA. At least in the case of battery and wireless, I don't think generating a challenge improve things over simply singing with EdDSA (but I don't have any measurements).

Agree that replay considerations are needed in the draft.

**Comment by gselander** [comment]
The protocol requires fresh nonces and there is a security consideration about not verifying freshness of nonces. The current version allows reuse of ephemeral keys and there is a security consideration about servers re-using ephemeral keys as one aspect of DoS mitigation. As mentioned, the cookie mechanism of DTLS is not favourable in constrained environments. What other replay protection / considerations / should we include?

**Comment by emanjon** [comment]
The current github version, soon to be submitted as version 10 now includes a reference to Echo. This provides protection against DoS be forcing the initiator to prove reachability at the network address.

Closing this issue as I think it is resolved.
