### ISSUE TITLE
Overview needs to be tighted up

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/EDHOC#19]
The current text appears to say that the overview is spread over three different sections.  2, 4.3 and 5.3.  Part of this may be sentence construction rather than a significant problem.  I would like to see a clear overview and put references to future sections where they are applicable rather than generally

**Comment by fpalombini** [comment]
Agree, it's going to come in the next update.

**Comment by fpalombini** [comment]
Included in commit 007ba1c

**Comment by jimsch** [comment]
Cannot see this in the commit that was referenced here.

**Comment by fpalombini** [comment]
Sorry, it was included first in commit e684d9b2 . Now the EDHOC overview is only on section 3, while the introduction to SIGMA-I protocol is in section 2. Sections 4.1 and 5.1 only add figures to make the next subsections easy to follow without jumping back to section 3.
