### ISSUE TITLE
Need error if ephemeral key is unsupported

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/EDHOC#24]
It is possible that there is no intersection of the ephemeral public key algorithm.  Should have a way to return this information as well as what is supported from the server to the client.

This also applies to the public key type.  For example, could support ECDH_SS_HKDF_256, but only for OKP keys and not for EC2 keys.  Additionally, could support for 256 bit keys, but not for 512 bit keys.

**Comment by emanjon** [comment]
Yes, I added a "Error Handling" section with a TODO in the latest update

**Comment by gselander** [comment]
I added verification of ephemeral public key type or algorithm in 207f40
