### ISSUE TITLE
Use SIGMA-I for both the symmetric and asymmetric cases

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/EDHOC#3]
Use SIGMA-I for both the asym and sym version of the protocol.  This is going to make the two versions more alike which makes implementation easier as well as protecting the id values which are sent in the symmetric key variant.  The key id may or may not leak any useful information, but long term ids sent in the message definitely does.

**Comment by emanjon** [comment]
Agree.

**Comment by fpalombini** [comment]
Included in commit 007ba1c
