### ISSUE TITLE
Provide method for defining kid of application derived key

### ISSUE THREAD

**Issue by gselander** [EricssonResearch/EDHOC#31]
Detail in section 3.2 how to obtain a kid related to an application derived key

**Comment by gselander** [comment]
(requested by 6tisch)

**Comment by jimsch** [comment]
Can you be more clear on what you are asking for here?  Do you want to derive the kid as in the B.1 or are you looking for the kid related to the PSK in which case I would probably say that is a really bad idea.

**Comment by gselander** [comment]
The key derivation allows for deriving keys for different application layer purposes using 'label' (or 'AlgorithmID' in COSE_KDF_Context). The question I got is if there is a canonical way to also derive a KID associated to the derived key.

I can think of the reverse - that first a KID is chosen, and then used to build up the string which becomes the label and which is used to derive the key. Any other idea?

**Comment by jimsch** [comment]
There would be absolutely no problem with doing the same thing for a kid.  You could define a label/alg name of "EDOCH Key Identifier" and use that to derive a kid assuming that it was always a fixed length.  I am not sure that there is going to be any win for doing so.

**Comment by gselander** [comment]
The issue was with getting short unique identifiers. But as I understand the use of EDHOC in 6tisch has changed and this is no longer requested. I close this issue and we may re-open it if the question comes back.
