### ISSUE TITLE
Key Derivation in 3.2 is under specified

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/EDHOC#34]
This section is missing the following items:

The strings for label are not specified.

Note:  I still recommend changing the ALG parameter instead of using labels.

**Comment by jimsch** [comment]
I will also note that the construction you have for other is unclear because of a missing grouping.  It currently looks like label is only appended for the last one and not for any of the other items.

**Comment by gselander** [comment]
Started resolving this in 7cd8cc

**Comment by gselander** [comment]
@jimsch: It was not intended to have a label for keys derived in the message exchange i.e. leave AlgorithmID empty. Do you see any issue with that?

**Comment by jimsch** [comment]
@gselander  - Yes, you need to do something to distinguish that you are doing both the algorithm and the IV and make sure that the values for these are distinct.  Leaving it empty is a bad idea

**Comment by gselander** [comment]
I made some updates recently, please review.

**Comment by jimsch** [comment]
Yes this looks fine, although you seem to have a formatting error on the last paragraph.

You also need to change algorihtmID to a tstr / int
