### ISSUE TITLE
Create option to prevent server from doing work

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/EDHOC#38]
Currently there is an easy way for a client to force a server to work without having to do any work itself.  This can be eased in part of the server is willing to re-use the DH key that it generates.  Another way to do something would be to do a force the client to do some type of POP before doing anything else.  

For now this is just a place holder so that I remember to think about this.

**Comment by gselander** [comment]
For PSK, the AEAD of message_1 provides a POP. We could omit the encryption of the extension and just keep the integrity protection.

**Comment by fpalombini** [comment]
@jimsch what do you say?

**Comment by jimsch** [comment]
First it does not address the same issue for when asymmetric keys are used, this means that it does not really solve the problem.

Looking at the dictionary attack, esp if you think you want to keep the PSK around long term is also an issue with this approach.

At this time, I am still leaning towards just documenting key re-use on the server depending on work load.

**Comment by jimsch** [comment]
I have had short discussion w/ EKR - there really is nothing in DTLS that is doing this today.  The only real thing they are dealing w/ is false flagging of ip addresses.  I think this can be closed as won't do unless somebody gives a real problem solution.
