### ISSUE TITLE
Add optional check on uniqueness of K_U

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/EDHOC#39]
Add an optional step for the server to do a check that K_U is unique.  This allows for a server to do a stronger check of replay of keys that it might want to do to avoid some types of DOS attacks as well as improving security of the protocol.

**Comment by gselander** [comment]
K_U is not defined, do you mean PSK or {K_1, K_2, K_3} or N_U?

**Comment by jimsch** [comment]
Sorry should have been N_U

**Comment by gselander** [comment]
I think this is already included, isn't it?

"Party V SHALL process message_1 as follows:
* Verify (OPTIONAL) that N_U has not been received before."
