### ISSUE TITLE
The requirement uniqueness needs to have careful justification anywhere it is used

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/EDHOC#4]
The use of the words 'unique' and 'uniquely' are highly problematical and need to be justified at any location where they are being used.  The problem is going to be that 1) if the identifier is really short (and thus reduces the transmission size) then collisions are going to be likely and 2) the entity that can check for a collision is not usually going to be the one that issues the identity and thus there is no way for enforcement of the requirement of uniqueness.  The only possible place where I can think that uniqueness is going to be an issue is for the shared key identifiers.

**Comment by gselander** [comment]
There are four occurances of the string "unique" in the current text. Is this still an issue?

   -  Party U’s SHALL be able to uniquely identify Party V’s public key using ID_V.
  -  Party V’s SHALL be able to uniquely identify Party U’s public key using ID_U.
- Party V SHALL be able to uniquely identify the PSK using KID.
 - When EDHOC is use to derive parameters for OSCOAP [I-D.ietf-core-object-security], the parties must make sure that the EDHOC session identifiers are unique Recipient IDs in OSCOAP.

**Comment by jimsch** [comment]
The last item can be taken care of in the protocol as the recipient identifier is going to be selected by the entity in question.  It can ensure that the value is unique.

For the key identifiers, what happens if a second entity attempts to register a new key with the same kid before the server expires out the old one - is this a replace, a reject or either depending on circumstances.  The key is what needs to be unique, one could attempt to use each of the keys identified until success is obtained.

**Comment by gselander** [comment]
I'll remove uniquely in the three first items.

**Comment by gselander** [comment]
I mean remove "uniquely".

**Comment by gselander** [comment]
Resolved in dbca2f
