### ISSUE TITLE
Use well-known prefix?

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/EDHOC#40]
Should the recommended path for the item use the well-known prefix or should it be a directory search term?

**Comment by gselander** [comment]
Why not do both? I.e. define  .well-known/core/edhoc, but also allow the application to define its own path to be discovered in an application defined way, e.g. using resource directory.

**Comment by jimsch** [comment]
No reason not to allow both.  Just wanted to be sure the issue was remembered.
