### ISSUE TITLE
PSK should be a one time use item

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/EDHOC#41]
There should be some text about the PSK being a one time use item.  If this is not done, then security considerations about the re-use of the secret needs to be provided so that people recognize the potential problem.

One thing that might be useful is to add a secret chaining mechanism by deriving an additional item ala appendix B.2

**Comment by gselander** [comment]
I don't understand which issue with PSK you are referring to. In general, two parties may use the same pre-shared key for encryption a number of times without any security issues.

**Comment by jimsch** [comment]
Allowing the key to be used multiple times, along with the encryption in the first message is what allows for a dictionary attack to occur.  If this is used long term, then it will slowly weaken as good base for security.   It would be better to generate a new shared secret at the end of the process and store that for use the next time if you want to re-run the protocol.

**Comment by gselander** [comment]
For each run of the protocol, new encryption keys and IVs are derived using fresh nonces. 

Eventually the PSK used in the key derivation will wear out, and that could merit a security consideration. And we could specify how to derive a new PSK replacing the old. But I can't think of a use case where such number of key exchanges are required. In particular changing PSK for each run of the protocol seems an overkill to me.
