### ISSUE TITLE
Certificates included in final derivation step

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/EDHOC#44]
Not sure if this needs to be done or not.  You are including the certificates in each of the intermediate message key derivations but no in the final secret derivation.  I don't know if they should or should not be included.  They are by proxy since the protocol would not run if they were different on the two sides.

**Comment by gselander** [comment]
I don't understand. Certificates are in ID_V which are included in the exchange_hash which is used in "other" in the final secret derivation.

**Comment by jimsch** [comment]
The ID_V can be any of  (kid, x5t, x5u)  or the certificate.  For the first three the certificate is not in the message.

If what you said was true then the certificate would be extraneous in the definition of aad_2 and aad)3

**Comment by gselander** [comment]
I see your point now. As you noted, if both parties perform the required processing steps and verified against the received messages, the protocol would not successfully complete if the certificate is different. The final secret derivation is dependent on the messages exchanged, the MAC which verifies the messages would be different with different certificates. 

We could include hashes of the certificates in the exchange_hash, but I'm not sure it is needed.

**Comment by emanjon** [comment]
Good point Jim, The protocol is now slightly changed so that the credential (a single X.509 or a COSE_KEY) is always included in the signature and therefore in all key derivations.
