### ISSUE TITLE
EDHOC Error message - what is the status code for it

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/EDHOC#45]
When sending back an EDHOC error message, what is the status code for it?  Are we using an error code or a success code as w/ normal messages?

**Comment by fpalombini** [comment]
If by status code you mean the underlying transfer protocol code (for example CoAP code), that would be a success code (non-error message). The reason for this is that EDHOC is independent of underlying protocols, it would be complicated, if possible at all, to define the behavior for each transport-application protocol EDHOC can be used with.

**Comment by jimsch** [comment]
You need to say that.  For COAP, does this mean that it should be Content or Changed?

**Comment by fpalombini** [comment]
Right, we need to clarify this in the appendix. To answer your question, I think the CoAP client should send the error in a POST CoAP request, the CoAP server should send it in the Changed response (same as if a non-error message was sent). Thanks for pointing this out.

**Comment by jimsch** [comment]
Odd -- I was assuming that error messages only went from server to client and not the other way around ....

**Comment by emanjon** [comment]
A lot of clarification is now added to github and will soon be submitted as version 10. 

The added text is in Error Handling section and in the Transferring EDHOC in CoAP section
