### ISSUE TITLE
S_U field in Message #2 - potentially can be removed

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/EDHOC#47]
If you have an external correlation mechanism, which CoAP does, then you do not need to have the S_U field in message #2 because you can already correlate the request (message #1) and response (mesage #2)

**Comment by emanjon** [comment]
This is now implemented on github and will soon be submitted as version 10

In message_2:

"C_U : bstr / nil,"

"C_U can be set to null if there is an external correlation mechanism (e.g. the Token in CoAP) that enables Party U to correlate message_1 and message_2."
