### ISSUE TITLE
Should EDHOC allow different security levels for authentication and message integrity?

### ISSUE THREAD

**Issue by emanjon** [EricssonResearch/EDHOC#56]
The current specification uses a single AEAD algorithm even if the AEAD algorithm is used for several different purposes. An application might want to use a stronger algorithm (e.g. AES-CCM-16-128-128) for authentication (i.e. EDHOC) and a algorithm (e.g. AES-CCM-16-64-128) with less overhead for the application data protection (e.g. OSCORE). The overhead of introducing this would be 1 byte in message_1 and 1 byte in message_2

**Comment by gselander** [comment]
This is going in the direction of more flexibility, but can be accomodated with ciphersuites (issue #57) without adding bytes. I don't know of any important use case though.

**Comment by emanjon** [comment]
Current agreement in LAKE req that AKA and OSCORE security algorithms should be independent

694acb3 implements this with cipher suites.
