### ISSUE TITLE
Should EDHOC introduce "cipher suites"?

### ISSUE THREAD

**Issue by emanjon** [EricssonResearch/EDHOC#57]
Klaus Hartke commented that it could make sense to introduce "cipher suites" in EDHOC. This have two benefits:

- Further reduce message overhead (-6 bytes in message_1 and -3 bytes in message_2)
- Reduce complexity of algorithm negotiation.

The disadvantage is of course flexibility. TLS 1.3 is partly going away from the "cipher suite" concepts, but I think that "cipher suites" makes more sense in contrained deployments (like EDHOC is designed for). EDHOC deployments will in likely support very few algorithms (maybe just one of each).

**Comment by gselander** [comment]
I think this makes sense, as long as the most relevant are pre-defined and it is not too cumbersome to define own ciphersuites. As usual there needs to be different ranges allocated according to different review critieria.

**Comment by emanjon** [comment]
Suggestions from both Salvador Pérez and Klaus Hartke to (optionally?) skip negotiation. The more I think about this, the more sense it makes.

Salvador Pérez: "Based on our experience, we propose that also removing the overhead due to security parameter negotiation could be an important optimisation, and relevant in many use cases where these parameters are available through an out-of-band process."

https://mailarchive.ietf.org/arch/msg/ace/fdRBb5blWT7g6NfrSHGS1pwY5mg

I think this is a good idea, I can see two ways to do this:

1. Let "parameters are available through an out-of-band process" be the only option. This saves 7 bytes in message_1 and 4 bytes in message_1

2. Introduce cipher suites and let "parameters are available through an out-of-band process" be cipher suite "0". Party U would then just send a single cipher suite to Party V and if Party V does not support that he responds with an errror indicating supported cipher suites.

**Comment by emanjon** [comment]
Given the comment from Michael Richardson

https://mailarchive.ietf.org/arch/msg/ace/2NNVIRSQmRf9nIh-Cqp54COvMis

"We need to do security parameter negotiation in order to be agile against
future algorithm attacks, and there will be algorithm attacks in the 20 to
40 year lifespans that we expect... and we need to leave space for replacing
the DH process with some QMDH process.  The CBOR encoding is really really
very nice for this, and I wish we had CBOR when we did IKEv2."

It seems like option  2. is the way to go. This would save 6 bytes in message_1 and 4 bytes in message_2

**Comment by emanjon** [comment]
Below is how the messages sizes will look like if this is implemented. Significant saving in the total number of bytes. 

```
                 PSK       RPK       x5t     x5chain
   --------------------------------------------------------------------
   message_1      43        38        38        38
   message_2      47       121       127       117 + Certificate chain
   message_3      12        86        92        82 + Certificate chain
   --------------------------------------------------------------------
   Total         102       245       257       237 + Certificate chains

                 Figure 6: Typical message sizes in bytes
```

The content of the messages would be something like this

```
  message_1 = (
     MSG_TYPE : int,
     C_U : bstr,
     CIPHER_SUITE : int,
     X_U : bstr,
     ? UAD_1 : bstr
   )

   data_2 = (
     MSG_TYPE : int,
     C_U : bstr / nil,
     C_V : bstr,
     X_V : bstr,
   )
```

**Comment by emanjon** [comment]
Cipher suites introduces with version -11
