### ISSUE TITLE
Signature algorithm negotiation should be allowed not used

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/EDHOC#6]
The current protocol description assumes that the signature algorithm is going to be the same for both entities.  There is no reason to assume this always going to be true.  The negotiation should be a set of algorithms that the party understands rather than attempting to agree on a single common one.  This means that Sig_Arr would be sent both directions and would be a list of acceptable algorithms.

**Comment by fpalombini** [comment]
Ok, we will include this in the next version.

**Comment by fpalombini** [comment]
Included in commit 007ba1c
