### ISSUE TITLE
Unify the CDDL on objects so that they match for symmetric and asymmetric

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/EDHOC#7]
Section 4.1.1 - Reverse the order of the fields SIG_arr and MAC_arr in alg_arr so that the same indexes can be used for both the symmetric and asymmetric cases.

Section 4.1.1 & 5.1.1 - Problem in that the same message names are used but the contents are not the same.  Merge the definitions together so that there is only one.  

Section 4.2.3 - combine pay1_3_rpk and pay1_3_cert into a single structure with an alternative option "ID_U: bstr / C_U:bstr" in the last line as the only difference is where the content comes from and not the structure of the array.

**Comment by fpalombini** [comment]
Ok

**Comment by fpalombini** [comment]
Included in commit 007ba1c
