### ISSUE TITLE
Remove nonce-array element

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/EDHOC#8]
Section 4.1.2 - I would like to see if we can get rid of the nonce-array element.  
    -- In message 2 asym - these can be moved to the PartyU_nonce and PartyV_nonce fields in the recipient structure.
   -- In message 3 asym - This would be both identification and replay detection.  Putting PartyV_nonce in the kid would work for identification, I am not sure what replay detection you are looking for but combining the nonce and the authentication tag might be a better detection than the pair of nonce values.

**Comment by fpalombini** [comment]
This is not relevant anymore, after update from commit 007ba1c
