### ISSUE TITLE
Change from ECDH-ES to ECDH-SS

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/EDHOC#9]
Section 4.2.1 - You should be using ECDH-SS rather than -ES for the algorithm.  This is really using short lived static keys rather than ephemeral keys from the perspective of the COSE messaging structure.  The key is being used in more than one message and thus COSE does not view this as a pure ephemeral.

Section 4.2.1 - The tag "E_V" should be "static key" (-2)

**Comment by emanjon** [comment]
Sure. If I understand corectly the only difference in COSE is a requirement to use server nonces (which EDHOC already fulfils).

**Comment by jimsch** [comment]
It would be use "sender nonce" not "server nonce" but otherwise correct.

**Comment by fpalombini** [comment]
Included in commit 007ba1c
