### ISSUE TITLE
Test vector discussion

### ISSUE THREAD

**Issue by martindisch** [EricssonResearch/EDHOC#94]
@emanjon Since you updated the test vectors, I've continued to check them against my implementation.

Another small inconsistency I found is that the example in A.2.1 mentions the plaintext as being a CBOR bstr, wrapping the sequence of ( ID_CRED_x, signature ):
> plaintext = << ID_CRED_x, signature >>

> For instance, if ID_CRED_x = { 4 : h’40’ } (CBOR encoding 0xA1044140) and signature = h’050607’ (CBOR encoding 0x43050607), then plaintext = h’414043050607’

This is another wrapping that isn't strictly necessary, as the plaintext could be a CBOR sequence without problems. And indeed, that's already the case in the test vectors, as `P_2` really is just a CBOR sequence. So I'm assuming that's another area where the next version of the spec will be adjusted to be in line with the test vectors? Just mentioning this to be sure.

The second issue is about `M_U`. It seems that while the CDDL representation
```
M_U =
[
  "Signature1",
  << { 4: h'a2' } >>,
  h'734bef323d867a12956127c2e62ade42c0f119e5487750c0c31fd093376dceed',
  {
    1:  1,
   -1:  6,
   -2:  h'424c756ab77cc6fdecf0b3ecfcffb75310c015bf5cba2ec0a236e6650c8ab9c7',
  },
]
```
is correct, the actual test vector has `TH_2` in the structure instead of `TH_3`, so you'll have to update that and regenerate the signature etc. that depend on it.

**Comment by emanjon** [comment]
Yes, the plaintext should be a CBOR Sequence. The specification needs update.

I fixed M_U and updated the test vectors.

**Comment by martindisch** [comment]
I'm done testing everything from the RPK section against my implementation and it checks out! Congrats, and thanks for putting in the work that allowed me to verify all this.

**Comment by emanjon** [comment]
Great news! Then we will start to add the test vectors to the main document.

Thanks for implementing, verifying the test vectors, and reporting all the errors!

/John
