### ISSUE TITLE
Test vectors for error, x5t and/or x5chain

### ISSUE THREAD

**Issue by emanjon** [EricssonResearch/EDHOC#97]

**Comment by emanjon** [comment]
The test vectors could also contain a few other parameters, like corr=2 and C_U = ""

**Comment by fpalombini** [comment]
it would be good with a test vector for an EDHOC error message.

**Comment by emanjon** [comment]
It would be good if the error test vectors included:

- Use of the index, i.e. 0, 0, 1 (support 0, 1 select 0).

- Use of non-registered suites, e.g. [ 3, 6, 2, -35, 2 ] (A256GCM, HMAC 384/384, P-384, ES384, P-384) which follows the US CNSA suite.

**Comment by emanjon** [comment]
x5t and/or x5chain in recent commits. I will open a new issue with error message
